from enum import Enum


class TOKEN_TYPE(Enum):
    NUMBER = "number"
    STRING = "string"
    IDENTIFIER = "identifier"
    UNARY_OPERATOR = "unary_operator"
    BINARY_OPERATOR = "binary_operator"
    EQUALS = "equals"
    OPEN_PARENTHESIS = "open_parenthesis"
    CLOSE_PARENTHESIS = "close_parenthesis"
    OPEN_BRACKET = "open_bracket"
    CLOSE_BRACKET = "close_bracket"
    LET = "let"
    IF = "if"
    THEN = "then"
    ELSE = "else"
    ELSE_IF = "else_if"
    END = "end"
    WHILE = "while"
    FOR = "for"
    FROM = "from"
    UNTIL = "until"
    STEP = "step"
    RETURN = "return"
    BREAK = "break"
    CONTINUE = "continue"
    NULL = "null"
    BOOLEAN = "boolean"
    READ = "read"
    PRINT = "print"
    FUNCTION = "function"
    COMMA = "comma"
    DOT = "dot"
    EOF = "eof"
